# website/scripts/generate_findings.py
"""Generate website/docs/reference/findings.md from the package catalogue.

`analysis/finding_help.py` is the source of truth for what every rule means;
this renders it as the published reference. Same arrangement as
`generate_api.py`, for the same reason: a page nobody hand-edits cannot drift
from the code it documents.

That is not a hypothetical here. The hand-maintained version of this page had
lost every blank line, grown a second `# ` title, and carried an orphaned
`sidebar_position: 4` in its body -- so all 194 rules rendered as one run-on
paragraph instead of a table, on the published site, for as long as it took
somebody to look. Its guard compared the SET of codes and stayed green
throughout.

Output is deterministic (no timestamps): rerunning on an unchanged tree
produces a byte-identical page, so drift shows up as a git diff.

Run from the repository root:

    uv run python website/scripts/generate_findings.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "src"))

from dbml_sharepoint.analysis.finding_help import FINDING_HELP  # noqa: E402

PAGE = REPO_ROOT / "website" / "docs" / "reference" / "findings.md"

# The narrative. Hand-written prose, kept here rather than in the data module
# because it is about the catalogue as a whole rather than about any rule.
PREAMBLE = """---
title: Findings
sidebar_position: 6
---

<!-- Generated by website/scripts/generate_findings.py. Do not edit by hand:
     the catalogue lives in src/dbml_sharepoint/analysis/finding_help.py. -->

# Finding catalogue

Every rule this build can report, by code.

The **code** is the identity. It is stable, it is what a test asserts on, and
it is what `dbml-sharepoint explain` takes. The message printed beside a
finding is prose for a human and may be reworded in any release, so nothing
should match on it.

A code names **what is wrong**, not where. The section, entity, view and
column are carried on the finding's `location`, which is normally the dotted
path the message opens with. Two rules that produce the same sentence for
different reasons therefore get two codes, and one rule reachable from two
sections keeps one.

Codes beginning `condition_` come from the shared condition grammar and can be
raised from any section that accepts a `when`: `views`, `form_visibility`,
`column_validation` and `list_validation` alike.

Look one up without leaving the terminal:

```bash
dbml-sharepoint explain unknown_column_type
```

| Code | Severity | What it means |
|---|---|---|
"""


def render() -> str:
    # Severity comes off the code, not from a column in this table. It is
    # declared once, on the FindingCode member, so the published page cannot
    # disagree with what the validator actually raises -- which it did, for
    # `extension_reported`, while severity was a per-call-site argument.
    rows = [
        f"| `{code}` | {code.severity} | {meaning} |"
        for code, meaning in sorted(FINDING_HELP.items())
    ]
    return PREAMBLE + "\n".join(rows) + "\n"


def main() -> None:
    # newline="\n" for the reason generate_api.write_page documents: text mode
    # emits CRLF on Windows, which reports the whole page as modified on every
    # regeneration and buries the one real change.
    PAGE.write_text(render(), encoding="utf-8", newline="\n")
    print(f"Generated {PAGE} with {len(FINDING_HELP)} rule(s)")


if __name__ == "__main__":
    main()
